2024/01/18 22:21:26 INFO mlflow.utils.conda: Conda environment mlflow-d6c04384fb9356865b6d231fc3cbd1b1b9b4863e already exists.
2024/01/18 22:21:26 INFO mlflow.projects.utils: === Created directory /tmp/tmpf163tzow for downloading remote URIs passed to arguments of type 'path' ===
2024/01/18 22:21:26 INFO mlflow.projects.backend.local: === Running command 'source /home/tblack/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-d6c04384fb9356865b6d231fc3cbd1b1b9b4863e 1>&2 && python run.py --trainval_artifact trainval_data.csv:latest \
              --val_size 0.2 \
              --random_seed 42 \
              --stratify_by neighbourhood_group \
              --rf_config /mnt/c/Users/treyd/Documents/Project-Build-an-ML-Pipeline-Starter/multirun/2024-01-18/22-21-18/0/rf_config.json \
              --max_tfidf_features 5 \
              --output_artifact random_forest_export' in run with ID '02f921fae0724f888346a29622848763' ===
2024/01/18 22:21:53 INFO mlflow.projects: === Run (ID '02f921fae0724f888346a29622848763') succeeded ===
[34m[1mwandb[39m[22m: [33mWARNING[39m Calling wandb.login() after wandb.init() has no effect.
[34m[1mwandb[39m[22m: [33mWARNING[39m Changes to your `wandb` environment variables will be ignored because your `wandb` session has already started. For more information on how to modify your settings with `wandb.init()` arguments, please refer to [34m[4mhttps://wandb.me/wandb-init[39m[24m.
[2024-01-18 22:21:54,209][HYDRA] 	#1 : main.steps='train_random_forest' modeling.random_forest.max_depth=10 modeling.random_forest.n_estimators=200
2024/01/18 22:21:56 INFO mlflow.utils.conda: Conda environment mlflow-d6c04384fb9356865b6d231fc3cbd1b1b9b4863e already exists.
2024/01/18 22:21:56 INFO mlflow.projects.utils: === Created directory /tmp/tmpsc3f402x for downloading remote URIs passed to arguments of type 'path' ===
2024/01/18 22:21:56 INFO mlflow.projects.backend.local: === Running command 'source /home/tblack/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-d6c04384fb9356865b6d231fc3cbd1b1b9b4863e 1>&2 && python run.py --trainval_artifact trainval_data.csv:latest \
              --val_size 0.2 \
              --random_seed 42 \
              --stratify_by neighbourhood_group \
              --rf_config /mnt/c/Users/treyd/Documents/Project-Build-an-ML-Pipeline-Starter/multirun/2024-01-18/22-21-18/1/rf_config.json \
              --max_tfidf_features 5 \
              --output_artifact random_forest_export' in run with ID '3ddc8b915e384545a789b8c34682df3d' ===
2024/01/18 22:22:41 INFO mlflow.projects: === Run (ID '3ddc8b915e384545a789b8c34682df3d') succeeded ===
[34m[1mwandb[39m[22m: [33mWARNING[39m Calling wandb.login() after wandb.init() has no effect.
[34m[1mwandb[39m[22m: [33mWARNING[39m Changes to your `wandb` environment variables will be ignored because your `wandb` session has already started. For more information on how to modify your settings with `wandb.init()` arguments, please refer to [34m[4mhttps://wandb.me/wandb-init[39m[24m.
[2024-01-18 22:22:41,847][HYDRA] 	#2 : main.steps='train_random_forest' modeling.random_forest.max_depth=50 modeling.random_forest.n_estimators=100
2024/01/18 22:22:44 INFO mlflow.utils.conda: Conda environment mlflow-d6c04384fb9356865b6d231fc3cbd1b1b9b4863e already exists.
2024/01/18 22:22:44 INFO mlflow.projects.utils: === Created directory /tmp/tmp9pd2u4wt for downloading remote URIs passed to arguments of type 'path' ===
2024/01/18 22:22:44 INFO mlflow.projects.backend.local: === Running command 'source /home/tblack/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-d6c04384fb9356865b6d231fc3cbd1b1b9b4863e 1>&2 && python run.py --trainval_artifact trainval_data.csv:latest \
              --val_size 0.2 \
              --random_seed 42 \
              --stratify_by neighbourhood_group \
              --rf_config /mnt/c/Users/treyd/Documents/Project-Build-an-ML-Pipeline-Starter/multirun/2024-01-18/22-21-18/2/rf_config.json \
              --max_tfidf_features 5 \
              --output_artifact random_forest_export' in run with ID 'fbb6e79ea39643689e027c051171807c' ===
2024/01/18 22:23:13 INFO mlflow.projects: === Run (ID 'fbb6e79ea39643689e027c051171807c') succeeded ===
[34m[1mwandb[39m[22m: [33mWARNING[39m Calling wandb.login() after wandb.init() has no effect.
[34m[1mwandb[39m[22m: [33mWARNING[39m Changes to your `wandb` environment variables will be ignored because your `wandb` session has already started. For more information on how to modify your settings with `wandb.init()` arguments, please refer to [34m[4mhttps://wandb.me/wandb-init[39m[24m.
[2024-01-18 22:23:14,014][HYDRA] 	#3 : main.steps='train_random_forest' modeling.random_forest.max_depth=50 modeling.random_forest.n_estimators=200
2024/01/18 22:23:16 INFO mlflow.utils.conda: Conda environment mlflow-d6c04384fb9356865b6d231fc3cbd1b1b9b4863e already exists.
2024/01/18 22:23:16 INFO mlflow.projects.utils: === Created directory /tmp/tmpr6x1k1wv for downloading remote URIs passed to arguments of type 'path' ===
2024/01/18 22:23:16 INFO mlflow.projects.backend.local: === Running command 'source /home/tblack/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-d6c04384fb9356865b6d231fc3cbd1b1b9b4863e 1>&2 && python run.py --trainval_artifact trainval_data.csv:latest \
              --val_size 0.2 \
              --random_seed 42 \
              --stratify_by neighbourhood_group \
              --rf_config /mnt/c/Users/treyd/Documents/Project-Build-an-ML-Pipeline-Starter/multirun/2024-01-18/22-21-18/3/rf_config.json \
              --max_tfidf_features 5 \
              --output_artifact random_forest_export' in run with ID '00b439d0d6dd494e886ed0e706d4d124' ===
2024/01/18 22:24:02 INFO mlflow.projects: === Run (ID '00b439d0d6dd494e886ed0e706d4d124') succeeded ===